### ISSUE TITLE
Watermarking Does Not Work

### ISSUE THREAD

**Issue by ChandraGedanggoreng** [Tonel/how-to-watermark-an-image-img-ly#1]
Hi,

I already cloned this repo and opened the index.html file.

After uploading an image, I only see the "Watermarked image 1 (image watermark)" and "Watermarked image 2 (text watermark)" but no other results.

Why does this watermarking not work as expected? Are there any files not included in the repo?

**Comment by Tonel** [comment]
Hi @ChandraGedanggoreng!
Maybe it is because you are using a watermark image that is too large/small. Also, what browser are you using?
Have you try to play with `context.translate(canvasWidth - image.width, canvasHeight - image.height);` to see what happens?

**Comment by ChandraGedanggoreng** [comment]
Hi, @Tonel . After opening console, I realized that it's caused by cross-origin policy. Sorry for jumping to the issue page too quickly. It's working nicely now. Thank you for this wonderful codes.

**Comment by Tonel** [comment]
@ChandraGedanggoreng thanks! I'm glad you were able to solve the problem!
